### PR TITLE
Optimised usage

### PR DESCRIPTION
**Pull request by polluks**

### CODE REVIEW

**Comment by boingball** [comment]
Looks a good way of optimizing the help screen, I'll test and merge tonight if it passes correctly on the tests.
Thanks for this! much appreciated.

**Comment by boingball** [comment]
Pull Request failed to compile - a few missing terminations in the print statement stopped it,
I've corrected the errors and it works
m68k-amigaos-gcc -c adate.c -o adate
adate.c: In function 'main':
adate.c:87:12: warning: missing terminating " character
   87 |            "               Supported formats:\n
      |            ^
adate.c:87:12: error: missing terminating " character
   87 |            "               Supported formats:\n
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
adate.c:91:12: warning: missing terminating " character
   91 |            "  TIME       - Specify the time (used with DATE).\n
      |            ^
adate.c:91:12: error: missing terminating " character
   91 |            "  TIME       - Specify the time (used with DATE).\n
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by polluks** [comment]
Indeed, the highlighting colours were obviously wrong.
The binary seems a little bit too big. How about stripping it?

**Comment by boingball** [comment]
Compiling with m68k-amigaos-gcc -s -Oz adate.c -o adate gives a binary of 148Kb
using strip after this doesn't change the size.
Not sure if theres better way of stripping it.

**Comment by polluks** [comment]
You have a complete symbol table,
see https://aminet.net/package/dev/misc/HunkShort
```
HUNK_HEADER
   nr of hunks: 3 (0-2)
   hunk 0 size: 147360 bytes
   hunk 1 size: 788 bytes
   hunk 2 size: 772 bytes
HUNK_CODE
   size: 147360 bytes
HUNK_(ABS)RELOC32
   1500 entrys to hunk 0
   186 entrys to hunk 1
   156 entrys to hunk 2
HUNK_SYMBOL
   _category :    $1E948
   ___exit :    $C8
   __isatty_r :    $22B04
   ___sf_fake_stdin :    $11672
   ___muldf3 :    $F248
   ___fixxfsi :    $23B36
   _sprintf :    $5168
   ___sfvwrite_r :    $11694
   ___d2b :    $16814
   __exit :    $C8
   ___truncdfsf2 :    $F2BC
   __read_r :    $16E98
   ___DTOR_LIST__ :    $23F58
   __getpid :    $21ABE
   _free :    $157C8
   _calculate_day_of_year :    $153C
   _strcat :    $53FC
   _strcmp :    $5568
   __sfread_r :    $1ACA0
   ___seofread :    $52AC
   ___muldi3 :    $22CB4
   ___fixdfdi :    $22D1C
   __jp2uc_l :    $11E92
   __ZN6MemMap4freeEPc :    $EECC
   __sscanf_r :    $5218
   ___fixunsdfsi :    $1E85C
   _DaysInMonth :    $2A38
   ___fixunsdfdi :    $22D70
   ___ssprint_r :    $1942C
   _calculate_week_number :    $160C
   ___sfp :    $11226
   ___lexf2 :    $F194
   __sungetc_r :    $1AB98
   ___unordsf2 :    $23D94
   ___ledf2 :    $F1E0
   __realloc_r :    $15744
   _calculate_year_month_day :    $2D7A
   __ctype_2 :    $F372
   __atoll_r :    $377A
   __etext :    $23FA0
   ___initcpp :    $27C
   ___gtxf2 :    $F194
   __write :    $16D28
   ___locale_mb_cur_max :    $4434
   __vfprintf_r :    $B2AC
   ___C_locale :    $44A6
   ___sfp_lock_acquire :    $11602
   ___gexf2 :    $F194
   _strtof_l :    $18C76
   ___fixdfsi :    $F204
   ___cmpsf2 :    $1E844
   ___subdf3 :    $F298
   ___swsetup_r :    $E588
   __Z11__sys_allocj :    $EB24
   ___fp_unlock_all :    $1161E
   ___extendsfdf2 :    $23DE0
   ___any_on :    $16A58
   _ungetc :    $1CC0A
   _cleanup_glue :    $16EE8
   ___jis_mbtowc :    $4C40
   __read :    $16D72
   __fwalk_reent :    $11AA0
   __wcsrtombs_r :    $E1F0
   __printf_r :    $4F4C
   __unlink :    $21B66
   ___sfp_lock_release :    $11604
   ___mcmp :    $1644A
   _puts :    $5104
   _strtoull :    $193E4
   ___truncxfdf2 :    $F0CC
   ___exit_fh :    $16DE8
   ___udivsi4 :    $371E
   ___EXIT_LIST__ :    $23F5C
   __mbtowc_r :    $466C
   ___umodsi3 :    $370C
   _strlcpy :    $5648
   ___sinit_lock_release :    $11608
   ___sflush_r :    $10EE4
   __open :    $16BD8
   ___multiply :    $16084
   _DateStampToDate :    $2AF0
   ___nedf2 :    $F1E0
   __fflush_r :    $1109E
   __fclose_r :    $21BD4
   ___nesf2 :    $1E844
   ___umoddi3 :    $233B0
   _fputwc :    $21DF0
   ___floatdidf :    $22DE4
   ___INIT_LIST__ :    $23F80
   ___extenddfxf2 :    $2390E
   __write_r :    $E554
   _adjust_date_time :    $108A
   __wctomb_r :    $E23C
   __fputwc_r :    $21DBC
   ___get_locale_env :    $40C8
   _open :    $16BD8
   ___floatsidf :    $F21C
   _strtol_l :    $60BA
   ___ascii_wctomb :    $E294
   ___gtsf2 :    $1E844
   _convert_unix_to_timeval :    $132A
   __calloc_r :    $15704
   ___swhatbuf_r :    $15666
   _strncpy :    $57D0
   ___b2d :    $16722
   ___udivdi3 :    $22E30
   ___ssvfscanf_r :    $9122
   __kill :    $21ABC
   _strtod_l :    $18C1C
   ___ltxf2 :    $F194
   __ZN4Tree3drlEPNS_4LeafES1_ :    $E834
   __jp2uc :    $11F44
   ___clz_tab :    $23E54
   ___divsi3 :    $36BC
   __ZN6MemMap6unlinkEPNS_4LeafE :    $EBEA
   __strdup_r :    $5608
   ___utf8_wctomb :    $E2C2
   __wcrtomb_r :    $DF74
   __strtoul_r :    $19070
   ___copybits :    $16A00
   __ZN6MemMap4findEi :    $EBB6
   ___sinit :    $115EE
   ___floatsixf :    $23AAA
   __ZN4Tree9fixRemoveEPNS_4LeafE :    $E9F2
   _vfiprintf :    $1E4D0
   _parse_date_string :    $1986
   _memcpy :    $15B78
   __ZN6RawMem5allocEj :    $EB52
   __strtod_l :    $172FC
   ___floatunsidf :    $1E8E0
   ___gedf2 :    $F1E0
   _memset :    $4ED8
   ___match :    $228A0
   _setlocale :    $448A
   __fstat_r :    $21E74
   __cleanup :    $115D8
   ___ZZZ_LIST__ :    $23F9C
   ___extendsfxf2 :    $239C4
   _calculate_days_since_1978 :    $280E
   _wcsnrtombs :    $1E7A4
   __isatty :    $16E00
   _frexp :    $170E4
   ___ascii_mbtowc :    $46D6
   __strtoull_r :    $1937A
   __ZN4Tree3drrEPNS_4LeafES1_ :    $E770
   __close_r :    $F338
   __ungetc_r :    $1CA92
   ___datadata_relocs :    $23FA0
   ___mdiff :    $16498
   ___swbuf_r :    $22B30
   ___cmpxf2 :    $F194
   ___sjis_wctomb :    $E3B2
   _fflush :    $11110
   _strtoull_l :    $193C4
   ___unordxf2 :    $2388C
   _ldiv :    $36BC
   ___swrite :    $52B0
   ___mulxf3 :    $23C4A
   __puts_r :    $5012
   __findenv_r :    $11AF8
   ___free_all :    $F048
   ___s2b :    $15ECA
   _lseek :    $21B5E
   _atoll :    $3764
   __mbrtowc_r :    $157DE
   _strtol :    $60DA
   _iswspace_l :    $11BC4
   ___lesf2 :    $1E844
   _strdup :    $55F4
   ___lo0bits :    $15FF0
   ___eqsf2 :    $1E844
   _strcasecmp :    $5388
   ___CTOR_LIST__ :    $23F54
   ___gtdf2 :    $F1E0
   _month_name_to_number :    $2F7A
   __Balloc :    $15CE0
   _wcsrtombs :    $E214
   __ZN4Tree6fixAddEPNS_4LeafE :    $E8FA
   _____start :    $0
   _calloc :    $1E92C
   ___mprec_tinytens :    $16ABE
   __ZN6MemMap3putEPNS_4LeafE :    $ECE6
   ___sf_fake_stdout :    $11652
   ___eucjp_wctomb :    $E420
   ___gesf2 :    $1E844
   ___initlibraries :    $1E4
   __uc2jp_l :    $11F52
   ___sclose :    $5376
   __ZN6MemMap5allocEj :    $ED52
   ___sprint_r :    $1CCC0
   ___floatunsixf :    $23AF0
   ___unorddf2 :    $F2D4
   __mprec_log10 :    $169A8
   _clearenv :    $21B88
   _parse_arguments :    $F8A
   ___subxf3 :    $23BD2
   __strtoll_r :    $647A
   __getenv_r :    $11B94
   __Z10__sys_freePc :    $EB0C
   ___multadd :    $15DF8
   ___hexdig :    $227A0
   ___exitlibraries :    $234
   _strtoul_l :    $190BA
   _realloc :    $16ECC
   ___submore :    $1C9F4
   _memchr :    $15A64
   __wcsnrtombs_l :    $1E5B0
   ___env_lock :    $21BD0
   __setlocale_r :    $412A
   _strncasecmp :    $56A0
   ___ratio :    $16910
   ___fp_lock_all :    $1160A
   _iswspace :    $11BB4
   ___env_unlock :    $21BD2
   _strtod :    $18C38
   _strtoll_l :    $64C4
   __free_r :    $F032
   _strchr :    $5458
   __strtod_r :    $18BDA
   ___eqdf2 :    $F1E0
   __lseek :    $21AD0
   __svfiprintf_r :    $195E6
   _malloc :    $157B4
   ___set_ctype :    $F364
   _fclose :    $21CE2
   ___fputwc :    $21CF4
   __lseek_r :    $154F8
   _strcpy :    $55E0
   _sscanf :    $51BC
   ___sjis_mbtowc :    $4A28
   __reclaim_reent :    $16F6A
   _memcmp :    $15B00
   __strtol_r :    $6070
   ___i2b :    $16066
   __cleanup_r :    $111B4
   ___mprec_bigtens :    $16AE6
   __fwalk :    $11A4C
   ___nexf2 :    $F194
   ___exitcpp :    $2AA
   ___cmpdf2 :    $F1E0
   ___pow5mult :    $1626E
   ___sread :    $5274
   __dtoa_r :    $F626
   __stext :    $0
   ___locale_ctype_ptr :    $4468
   ___divdf3 :    $1E820
   ___divxf3 :    $23CC2
   __malloc_r :    $F024
   ___lshift :    $1636A
   ___sccl :    $1718C
   ___ssvfiscanf_r :    $1AD6C
   ___sseek :    $5336
   ___smakebuf_r :    $1552C
   _strtoll :    $64E4
   _set_system_time :    $2BD8
   __wcsnrtombs_r :    $1E74E
   ___negxf2 :    $23D3A
   _timeval_to_datestamp :    $13FC
   ___ltsf2 :    $1E844
   _localeconv :    $154D6
   ___hexnan :    $228E6
   _wcrtomb :    $E0B2
   _strncmp :    $5728
   _callfuncs :    $118
   __Bfree :    $15DA4
   ___hi0bits :    $15F8A
   __close :    $16CC4
   _write :    $16D28
   _stpncpy :    $17264
   ___jis_wctomb :    $E4B4
   __ZN4Tree4Leaf4prevEv :    $E732
   ___sf_fake_stderr :    $11632
   ___sinit_lock_acquire :    $11606
   ___modsi3 :    $36B0
   ___swbuf :    $22C66
   ___udivsi3 :    $3718
   _strtoul :    $190DA
   _calculate_day_of_week :    $1508
   __vfiprintf_r :    $1CD14
   _div :    $36BC
   _ioctl :    $21B84
   _strlen :    $568C
   _mbrtowc :    $15922
   _read :    $16D72
   _memmove :    $15BE8
   __fstat :    $21B62
   ___mprec_tens :    $16B0E
   ___ssrefill_r :    $1AC52
   _exit :    $C8
   __localeconv_r :    $154B4
   ___localeconv_l :    $154A8
   __svfprintf_r :    $6568
   ___init_fh :    $16DBC
   ___locale_ctype_ptr_l :    $445E
   _printf :    $4FAC
   ___ltdf2 :    $F1E0
   ___loadlocale :    $38E4
   __ZN4Tree4Leaf4nextEv :    $E6F4
   _show_date_unix :    $1478
   ___utf8_mbtowc :    $471A
   __sprintf_r :    $5118
   ___eqxf2 :    $F194
   _nanf :    $1725C
   ___ulp :    $166D0
   _strtof :    $18D4C
   __ZN4Tree2rrEPNS_4LeafES1_ :    $E7E6
   _show_date :    $3036
   ___sfmoreglue :    $111CC
   ___adddf3 :    $1E7FC
   ___addxf3 :    $23B5A
   ___mulsi3 :    $F26C
   __global_impure_ptr :    $11BB0
   __ZN4Tree2rlEPNS_4LeafES1_ :    $E8AA
   _strstr :    $5BD2
   _main :    $818
   ___eucjp_mbtowc :    $4B0A
   _vfprintf :    $DE96
   ___gethex :    $21F6A
   _close :    $16CC4
   ___truncxfsf2 :    $23A7E
HUNK_END
HUNK_DATA
   size: 788 bytes
HUNK_(ABS)RELOC32
   47 entrys to hunk 0
   1 entrys to hunk 1
   1 entrys to hunk 2
HUNK_SYMBOL
   _MathIeeeDoubBasBase :    $2F8
   ___LIB_LIST__ :    $2EC
   _DOSBase :    $2F0
   _MathIeeeDoubTransBase :    $300
   _MathIeeeSingBasBase :    $308
   _environ :    $2E8
   ___global_locale :    $68
   _day_names :    $0
   __edata :    $314
   ___default_locale :    $1D0
   _day_abbr :    $1C
   ___ZZZ_DLIST__ :    $310
   __sdata :    $0
   __impure_ptr :    $1F4
   __ctype_ :    $1F0
HUNK_END
HUNK_BSS
   size: 772 bytes
HUNK_SYMBOL
   ___maxfh :    $2F0
   __WBenchMsg :    $8
   ___argv :    $0
   __PathLocale :    $24
   __end :    $304
   ___commandlen :    $10
   __bss_start :    $0
   ___fh :    $2F4
   _SysBase :    $18
   ___commandline :    $C
   _errno :    $2FC
   _initial_env :    $300
   ___argc :    $14
HUNK_END
done.

**Comment by boingball** [comment]
There must be a bug in GCC v13.2 latest from bebbo to keep the symbols in: I assume this doesn't happen if it's compiled with an older GCC. I don't have an older gcc on my laptop to test this: my workstation has gcc v6 as default. If it compiles to a smaller version with that without the symbols I'll log it to bebbo as a bug.

**Pull request merged**
